'use client';

import classNames from 'classnames';
import React, { ChangeEvent, useEffect, useId, useMemo, useState } from 'react';
import { FileInterface } from '../../component.interface';
import styles from '../../component.module.css';
import { useUpload } from '../../hooks/hook';
import { generateUniqueId } from '../../utils/id/util';
import { UploadInputProps } from './component.interface';

export function UploadInput({ ...rest }: UploadInputProps) {
  // Autogenerated id
  const { setId, setName } = useUpload();

  const uniqueId = rest?.id ?? useId();
  const uniqueName = rest?.name ?? uniqueId;

  useEffect(() => {
    setId(uniqueId);
    setName(uniqueName);
  }, [setId, setName, uniqueId, uniqueName]);

  // Upload
  const isControlled = rest?.value !== undefined;
  const [internalFiles, setInternalFiles] = useState<any[]>(rest?.value ?? []);
  const files = isControlled ? rest?.value ?? [] : internalFiles;

  const isLoading = useMemo(() => {
    return files.some((file: any) => file?.isLoading === true);
  }, [files]);

  const setFiles = (newFiles: any[]) => {
    if (!isControlled) {
      setInternalFiles(newFiles);
    }
    rest?.onChange?.(newFiles);

    const nextIsLoading = newFiles.some(
      (file: any) => file?.isLoading === true
    );
    if (nextIsLoading !== isLoading) {
      rest?.onLoadingChange?.(nextIsLoading);
    } else {
      rest?.onLoadingChange?.(nextIsLoading);
    }
  };

  const handleFileChange = async (e: ChangeEvent<HTMLInputElement>) => {
    if (!e.target.files || e.target.files.length === 0) return;

    const fileList = Array.from(e.target.files);
    const newFiles: FileInterface[] = [];

    // Находим максимальную текущую позицию
    const maxPosition =
      files.length > 0
        ? Math.max(...files.map((file: any) => file.position))
        : -10;

    for (let i = 0; i < fileList.length; i++) {
      const file = fileList[i];
      const fileId = generateUniqueId();

      // Создаем временный объект файла с состоянием загрузки
      const newFile: FileInterface = {
        id: fileId,
        position: maxPosition + 10 + i * 10,
        src: '',
        name: file.name,
        isLoading: true,
      };

      newFiles.push(newFile);
    }

    // Добавляем новые файлы к текущим
    const updatedFiles = [...files, ...newFiles];
    setFiles(updatedFiles);

    // Загрузка файлов на CDN
    if (!rest?.cdn) {
      console.warn('CDN configuration is not provided');
      return;
    }

    try {
      const formData = new FormData();

      // Добавляем все файлы в одну FormData для bulk загрузки
      fileList.forEach((file) => {
        formData.append('file', file);
      });

      const response = await fetch(rest?.cdn?.url, {
        method: rest?.cdn?.method,
        headers: {
          Authorization: `Bearer ${rest?.cdn?.token}`,
        },
        body: formData,
      });

      const result = await response.json();

      if (!response.ok) {
        throw new Error(result.message || 'Ошибка загрузки файлов');
      }

      // Результат - массив объектов с информацией о загруженных файлах
      const cdnFiles: FileInterface[] = Array.isArray(result)
        ? result
        : [result];

      // Обновляем информацию о файлах
      const updatedFilesList = [...updatedFiles];
      const baseLength = files.length;

      cdnFiles.forEach((cdnFile: FileInterface, index: number) => {
        const fileIndex = baseLength + index;

        if (fileIndex < updatedFilesList.length) {
          updatedFilesList[fileIndex] = {
            ...updatedFilesList[fileIndex],
            src: cdnFile.src ?? '',
            error: cdnFile.error ?? '',
            isLoading: false,
          };
        }
      });

      setFiles(updatedFilesList);
    } catch (error) {
      const updatedFilesList = [...updatedFiles];
      const baseLength = files.length;

      newFiles.forEach((_, index) => {
        const fileIndex = baseLength + index;

        updatedFilesList[fileIndex] = {
          ...updatedFilesList[fileIndex],
          error:
            error instanceof Error ? error.message : 'Ошибка загрузки файла',
          isLoading: false,
        };
      });

      setFiles(updatedFilesList);
    }
  };

  return (
    <input
      {...rest}
      id={uniqueId}
      name={uniqueName}
      type="file"
      onChange={handleFileChange}
      className={classNames(
        'mosuk-upload-input',
        styles.input,
        rest?.className
      )}
    />
  );
}
